[package]
name = "vertigo-forms-storybook"
version = "0.1.0"
authors = ["Micha≈Ç Pokrywka <wolfmoon@o2.pl>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vertigo = "0.9"
vertigo-forms = { path = ".." }
