[package]
name = "vertigo-forms-example-manual-form"
version = "0.1.1"
authors = ["Micha≈Ç Pokrywka <wolfmoon@o2.pl>"]
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
vertigo = "0.9"
vertigo-forms = { path = "../.." }
